---
- name: Update cache and Install utility Packages
  ansible.builtin.dnf: 
    name: "{{server.packages}}"
    # bugfix: yes
    state: present
    update_cache: yes

#- name: Set default locale
#  ansible.builtin.command: localectl set-locale LANG={{server.locale}}


- name: Set the hostname
  ansible.builtin.hostname: 
    name: "{{server.hostname}}"

- name: Update /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: '127.0.0.1'
    line: 127.0.0.1 localhost {{server.hostname}}
    owner: root
    group: root
    mode: '0644'
  
- name: Set the hostname in /etc/hostname
  ansible.builtin.shell: echo {{server.hostname}} > /etc/hostname
  when: server.hostname is defined


- name: Remove default postgresql module and its dependencies
  ansible.builtin.command: dnf module disable -y postgresql

- name: Remove default mariadb and its dependencies
  ansible.builtin.command: dnf module disable -y mariadb

- name: Remove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes

# baseurl is URL to the directory where the yum repository’s ‘repodata’ directory lives.
- name: Add official mariaDB repo
  ansible.builtin.yum_repository:
    name: mariaDB
    description: MariaDB 10.6 RedHat repository
    baseurl: https://mariadb.mirror.liquidtelecom.com/yum/10.6/rhel/8/x86_64/
    gpgkey: https://mariadb.mirror.liquidtelecom.com/yum/RPM-GPG-KEY-MariaDB
    module_hotfixes: yes
    enabled: no
    protect: yes

- name: Add official Postgres repo
  ansible.builtin.yum_repository:
    name: postgres13
    description: Official Postgresql 13 RedHat repository
    baseurl: https://download.postgresql.org/pub/repos/yum/13/redhat/rhel-8-x86_64/
    gpgkey: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-13
    module_hotfixes: yes
    enabled: no
    protect: yes

# should be in mysql role -- config section
- name: Ensure directory exist for MariaDB log file
  ansible.builtin.file:
    path: /var/log/mariadb
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

# should be in mysql role -- config section
- name: Ensure directory exist for MariaDB PID file
  ansible.builtin.file:
    path: /var/run/mariadb
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'
