---
- hosts: all
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - geerlingguy.repo-remi
    - geerlingguy.pip
    - fadinggiant.config
    - geerlingguy.git
    - geerlingguy.nodejs
    - geerlingguy.mysql
    - geerlingguy.postgresql
    - geerlingguy.memcached
    - geerlingguy.redis
    - fadinggiant.openssl
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-xdebug
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.adminer
    - geerlingguy.security
    - geerlingguy.firewall